#!/usr/bin/env bash

host_address="178.79.188.82" # jammon.philcrump.co.uk
host_port=44333

port_path="$(ls /dev/ttyACM*)"

if [ -z $port_path ];
then
	echo "No serial device found!";
	exit;
fi

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)";
cd "$source_dir";

if [ $? -eq 0 ];
then
	./jammon -r -d ${port_path} -M -H ${host_address} -P ${host_port};
fi
